os:
  - linux
  - osx

# Linux system
# 'bionic' is latest Ubuntu LTS available on Travis
dist: bionic

# macOS system
# 'xcode11.2' is macOS 10.14 xcode 11B41
osx_image: xcode11.2
  
language: minimal

addons:
  apt:
    packages:
      - sbcl
  homebrew:
    update: true
    packages:
      - sbcl

install:
  - echo $(pwd)
  - bash -x ${TRAVIS_BUILD_DIR}/ci/asdf-configure.bash
  - bash -x ${TRAVIS_BUILD_DIR}/ci/quicklisp-install.bash


script:
  - date
  - sbcl --eval '(lisp-implementation-version)' --eval '(asdf:asdf-version)' --eval '(exit :code 0)'
  - sbcl --eval '(ql:quickload :warno)' --eval '(exit :code 0)'
  - sbcl --eval '(asdf:load-system :warno)' --eval '(exit :code 0)'
  - date
