* Problems

Problems that Zach Beane and Mark Evenson have with how Quicklisp and
ASDF interact.

** (Xach) compile warnings should not always be fatal conditionally
<https://lispblog.xach.com/post/104872127228/a-verbosity-conundrum>

*** (Xach)
<https://twitter.com/xach/status/1204038946503741440?s=20>
To simplify: I want to establish a dynamic environment (variables and
handler binds) around each call to LOAD-SYSTEM, including
recursively. I haven't found a way yet.

*** Problem transcription (easye)
We need to define a predicate for the recursive transversal of the
planned ASDF graph that allows us to select restarts for whether any
given section of the build machinery fails, and signals a condition.  

*** Demonstration of problem (Xach)

#+BEGIN_SRC lisp
   #p"<file:warno.asd>"
#+END_SRC

*** TODO construct predicate

** (easye) :DEFSYSTEM-DEPENDS-ON clauses should use Quicklisp network load transparently

Involves patching <https://github.com/quicklisp/quicklisp-client>.

Zach's work on this can be seen in <https://github.com/quicklisp/ddo-bug>.

** (everyone) I shouldn't care that Quicklisp uses ASDF2

Tell us what doesn't work for you.

* Examples

#+BEGIN_SRC lisp
(when (asdf:find-system :prove)
  (ql:uninstall :prove))
(ql:quickload :disprove)
#+END_SRC

#+BEGIN_SRC lisp
(loop :for system :in '(:custodes :warno)
   :when
      (asdf:find-system system)
   :do
     (ql:uninstall system)
   :doing
     (ql:quickload system))
#+END_SRC

* Colophon

#+BEGIN_EXAMPLE
    Mark <evenson.not.org@gmail.com>
    Created: <2019-12-09 Mon>
    Revised: <2019-12-11 Wed 07:52>
#+END_EXAMPLE


